export * from "./types";
export * from "./constants";
export {
  DEFAULT_SIMULATION_CONFIG,
  DISTRIBUTION_POLICY_LABELS,
  SEASONS,
  SEASON_LABELS,
  parseSimulationConfig,
  seasonWeights,
  simulationConfigSchema,
  type DistributionPolicy,
  type Season,
  type SimulationConfig,
} from "./config";
export {
  CORE_RESOURCES,
  EXTRA_RESOURCES,
  RESOURCES,
  RESOURCE_LABELS,
  RESOURCE_VALUE,
  addBundle,
  addResource,
  bundleEntries,
  bundleTotal,
  clampResource,
  consumeResource,
  emptyStock,
  getResourceAmount,
  hasRequiredResources,
  missingResources,
  normalizeStock,
  payResources,
  roundStock,
  stockToBundle,
  stockValue,
  transferResource,
  type CoreResource,
  type ExtraResource,
  type GoodsBag,
  type ResourceKind,
} from "./stock";
export { Rng, deriveRng, hashCode, hashFloat, type RngState } from "./prng";
export {
  createWorld,
  hasWaterAccess,
  pickBalancedStartingCells,
  pickStartingCells,
  startingAreaQuality,
  type CreateWorldOptions,
} from "./world-generator";
export * from "./identity";
export {
  BELIEF_MIN_POPULATION,
  BELIEF_MIN_SPIRITUALITY,
  BELIEF_TYPE_LABELS,
  SYNCRETISM_YEARS,
  adherenceDrift,
  applyDerivedEffects,
  beliefContextOf,
  beliefDistance,
  beliefEffects,
  beliefTypeFor,
  canFoundBelief,
  canSyncretize,
  foundBelief,
  updateBeliefs,
  type BeliefContext,
} from "./belief";
export {
  AGREEMENT_LABELS,
  NEGOTIABLE,
  activeAgreements,
  cancelOrphanAgreements,
  canSign,
  emptyReputation,
  expireAgreements,
  hasAgreement,
  pairKey,
  reputationOf,
  signAgreement,
  signingChance,
  updateAgreements,
  updateReputation,
  violateAgreement,
} from "./agreements";
export {
  CRISIS_RESPONSE_LABELS,
  chooseCrisisResponse,
  computeResilience,
  overallResilience,
  rankCrisisResponses,
  resilienceInputOf,
  type CrisisResponse,
  type CrisisSituation,
  type ResilienceInput,
  type ResilienceProfile,
} from "./resilience";
export {
  KNOWLEDGE_DECAY,
  KNOWLEDGE_FORGET,
  KNOWLEDGE_SOURCE_LABELS,
  MAX_ESTIMATE_ERROR,
  SIGHT_DISTANCE,
  ageKnowledge,
  attemptEspionage,
  emptyKnowledge,
  estimate,
  knowledgeIndex,
  knowledgeKey,
  perceivedPower,
  refreshKnowledge,
  spyEffort,
  spySuccessChance,
  truthOf,
  updateKnowledge,
  viewOf,
  wantsToSpy,
  type ContactChannels,
  type KnowledgeTruth,
  type KnowledgeView,
} from "./knowledge";
export {
  ANCHOR_MAX_AGE,
  MAX_ANCHORS,
  anchor,
  anchored,
  causesFrom,
  releaseAnchor,
  warKey,
  type CausalAnchor,
} from "./causality";
export { TECH_VARIANTS, localTechName, variantByKey, variantFor, type TechVariant } from "./tech-variants";
export {
  SCENARIOS,
  SCENARIO_NAMES,
  buildScenario,
  isScenarioName,
  relocateTribe,
  type ScenarioDefinition,
  type ScenarioName,
} from "./scenarios";
export {
  checkDeterminism,
  checkRuns,
  measureRun,
  runAndMeasure,
  type CheckResult,
  type CheckSeverity,
  type RunMetrics,
} from "./scenario-metrics";
export * from "./placement";
export * from "./politics";
export * from "./fusion";
export * from "./identity/composite";
export * from "./language/italian";
export * from "./language/format";
export { generateTerrain, computeHabitability } from "./terrain";
export {
  runSimulation,
  runTick,
  createContext,
  buildCommunities,
  collectStats,
  collectCivilizationStats,
  type RunOptions,
} from "./simulation-engine";
export {
  LOSS_POPULATION_MARGIN,
  LOSS_RATE,
  LOSS_THRESHOLD,
  REDISCOVERY_SPEED,
  RESEARCH_BASE,
  RESEARCH_FOCUS,
  RESEARCH_KNOWLEDGE_WEIGHT,
  TECHNOLOGIES,
  TECH_BY_ID,
  TECH_CATEGORY_LABELS,
  TECH_STATUS_LABELS,
  advanceAdoption,
  allocateResearch,
  canBeLost,
  canBeRediscovered,
  canDiffuse,
  canResearch,
  decayTechnologies,
  knowledgeStrain,
  neutralEffects,
  researchAptitude,
  researchBudget,
  researchWeight,
  techAffinity,
  techEffects,
  techNeeds,
  techProfile,
  techStatus,
  tribeEffects,
  type ResearchBudgetInput,
  type TechCategory,
  type TechConditionInput,
  type TechDriver,
  type TechEffects,
  type TechNeeds,
  type TechProfile,
  type TechStatus,
  type TechnologyDefinition,
  type TechnologyProgressResult,
} from "./technology";
export { resolveBattle, sidePower, type BattleOutcome, type CombatSide } from "./warfare";
export { birthProbability, baseMortality, related } from "./population";
export { EVENT_TYPE_LABELS, IMPORTANCE_LABELS, formatYear, describePlace } from "./events";
export {
  serializeWorld,
  deserializeWorld,
  deserializeState,
  cloneWorld,
  normalizeState,
  hashWorld,
  STATE_VERSION,
  MIN_SUPPORTED_STATE_VERSION,
  SIMULATION_VERSION,
} from "./serialization";
export {
  SIMULATION_VERSION as ENGINE_VERSION,
  deriveCulture,
  deriveDeposits,
  migrateState,
  normalizeCell,
  normalizePerson,
  normalizeRelationship,
  normalizeCivilization,
  normalizeSettlement,
  normalizeSkills,
  normalizeTribe,
  tierFromLevel,
} from "./normalize";
export { checkInvariants, assertInvariants, InvariantError, type InvariantOptions } from "./invariants";
export {
  CULTURE_DISPOSITION_RANGE,
  CULTURE_LABELS,
  CULTURE_RECORD_THRESHOLD,
  CULTURE_TRAITS,
  MAX_CULTURE_HISTORY,
  cultureDisposition,
  culturalDistance,
  initialStability,
  randomCulture,
  recordCultureChanges,
  updateCulture,
  type CulturePressure,
} from "./culture";
export {
  DYNASTY_MIN_POPULATION,
  MAJORITY_AGE,
  SUCCESSION_LAW_LABELS,
  SUCCESSION_OUTCOME_LABELS,
  canFoundDynasty,
  endDynasty,
  ensureDynasty,
  heirsOf,
  isEligibleLeader,
  leaderScore,
  leaderScoreParts,
  restoreDynasty,
  successionCrisisRisk,
  successionLawOf,
  successionSituation,
  type SuccessionRiskInput,
} from "./leadership";
export { epidemicRisk, type EpidemicRisk } from "./crises";
export {
  annualYieldAt,
  averageTemperature,
  cellClimate,
  climateAt,
  climateStress,
  computeSeasons,
  definingSeason,
  hazardsAt,
  seasonYieldAt,
  winterConsumptionFactor,
  winterMortalityFactor,
} from "./climate";
export { areaDeposits, areaQuality, workArea } from "./resources";
export { foodNeed, housingCapacity, storageCapacity, type Production } from "./economy";
export {
  FOUNDING_REASON_LABELS,
  MAX_NOTABLE_EVENTS,
  SPECIALIZATION_LABELS,
  emptyHistory,
  foundingReasonFor,
  recordDestruction,
  recordReconstruction,
  rememberEvent,
  specializationsOf,
  survivingInfrastructure,
  updateSettlementHistory,
} from "./settlement-history";
export {
  RUINS_FORGOTTEN_AFTER,
  reviveSettlement,
  ruinsAt,
  SETTLE_AFTER_YEARS,
  TIER_REQUIREMENTS,
  computeLevel,
  tierOf,
  type TierRequirement,
} from "./settlements";
export { cellAt, distance, inBounds, clamp, round } from "./grid";
