"use client";

import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { api, queryKeys } from "@/lib/client/api";
import { fmtYear, GOVERNMENT_LABELS } from "@/lib/client/format";
import {
  CIV_STATUS_LABELS,
  IDENTITY_DISCLAIMER,
  PLACEMENT_SIZE_LABELS,
  IDENTITY_TYPE_LABELS,
  TECH_METHOD_LABELS,
} from "@/lib/client/identity";
import type { TribeDTO, WorldDetail } from "@/lib/dto";
import { useWorldUi } from "@/lib/client/store";
import { IdentityEmblem } from "./identity-emblem";
import { EntityLink, Facts, SubHeading } from "./stat-bits";

/**
 * Identity of a people and the history it produced in this world. The two are kept visibly
 * apart: the identity is static flavour, everything under "Storia in questo mondo" was
 * generated by the simulation.
 */
export function TribeIdentitySection({ tribe, detail }: { tribe: TribeDTO; detail: WorldDetail }) {
  const { select } = useWorldUi();
  const worldId = detail.world.id;
  const identity = detail.identities.find((i) => i.key === tribe.identityId);
  const entry = detail.roster?.entries.find((e) => e.tribeId === tribe.id);
  // Keyed on the tick: the facts change only when the world advances.
  const civ = useQuery({
    queryKey: [...queryKeys.civilization(worldId, tribe.id), detail.world.currentTick],
    queryFn: () => api.civilization(worldId, tribe.id),
    enabled: identity !== undefined,
    staleTime: Infinity,
  });
  const absorbedBy = detail.tribes.find((t) => t.id === tribe.absorbedByTribeId);
  const parent = detail.tribes.find((t) => t.id === tribe.parentTribeId);
  const absorbed = tribe.absorbedIdentityIds
    .map((key) => detail.identities.find((i) => i.key === key)?.displayName ?? key)
    .join(", ");
  const startingTech = detail.discoveries.find((d) => d.tribeId === tribe.id && d.method === "starting");
  const startingTechName = startingTech
    ? (detail.technologies.find((t) => t.id === startingTech.techId)?.name ?? startingTech.techId)
    : null;

  const composite = detail.composites.find((c) => c.id === tribe.identityId);
  if (composite) return <CompositeIdentitySection tribe={tribe} detail={detail} compositeId={composite.id} />;

  if (!identity) {
    return (
      <p className="text-muted mb-3 text-xs">
        {IDENTITY_TYPE_LABELS[tribe.identityType] ?? "Popolo inventato"}: nome e storia sono interamente
        procedurali.
      </p>
    );
  }

  return (
    <section aria-label="Identità e storia" className="mb-2">
      <div className="mb-2 flex items-center gap-2">
        <IdentityEmblem emblemKey={identity.emblemKey} color={tribe.color} />
        <div className="min-w-0">
          <p className="text-muted text-xs">Identità</p>
          <p className="truncate font-serif text-lg leading-tight">{identity.displayName}</p>
        </div>
        {civ.data && (
          <Badge className="ml-auto">{CIV_STATUS_LABELS[civ.data.status] ?? civ.data.status}</Badge>
        )}
      </div>
      <SubHeading>Storia in questo mondo</SubHeading>
      <Facts
        items={[
          [
            "Fondata",
            entry ? `al tick 0 (${fmtYear(tribe.foundedYear)})` : `nel ${fmtYear(tribe.foundedYear)}`,
          ],
          [
            parent ? "Nata da" : "Origine",
            parent ? (
              <EntityLink color={parent.color} onClick={() => select({ kind: "tribe", id: parent.id })}>
                {parent.name}
              </EntityLink>
            ) : (
              "Roster di fondazione"
            ),
          ],
          ["Leader iniziale", entry?.initialLeaderName ?? "—"],
          ["Tecnologia iniziale", startingTechName ?? (parent ? "Ereditata" : "—")],
          ["Primo insediamento", civ.data?.firstSettlement?.name ?? (civ.isPending ? "…" : "Non ancora")],
          ["Governo attuale", GOVERNMENT_LABELS[tribe.government] ?? tribe.government],
          ...(entry
            ? ([
                [
                  "Qualità della partenza",
                  `${Math.round(entry.startQuality * 100)}%${entry.startWater ? " · acqua vicina" : " · senza acqua vicina"}`,
                ],
                ...(entry.fertility !== undefined
                  ? ([
                      [
                        "Fertilità · risorse · clima",
                        `${Math.round(entry.fertility * 100)}% · ${Math.round((entry.resources ?? 0) * 100)}% · ${
                          (entry.climatePenalty ?? 0) > 0.15 ? "rigido" : "mite"
                        }`,
                      ],
                    ] as [string, string][])
                  : []),
              ] as [string, string][])
            : []),
          ["Storia reale applicata", "No"],
          ["Identità storica come ispirazione", "Sì"],
        ]}
      />
      {entry?.placementFallback && (
        <p
          role="note"
          className="border-ochre/40 bg-ochre/10 text-ochre mt-2 rounded-md border px-2 py-1 text-xs"
        >
          Partenza di ripiego: la mappa{" "}
          {PLACEMENT_SIZE_LABELS[detail.roster?.placement?.band.mapSize ?? "medium"] ?? ""} non offriva
          abbastanza posizioni nella fascia di qualità preferita
          {detail.roster?.placement
            ? ` (≥ ${Math.round(detail.roster.placement.band.preferredMin * 100)}%, scarto ≤ ${Math.round(
                detail.roster.placement.band.preferredMax * 100,
              )} punti)`
            : ""}
          . Questo popolo parte da una cella valida ma meno omogenea rispetto agli altri.
        </p>
      )}
      {absorbedBy && (
        <p className="text-muted mt-2 text-xs">
          Assorbita da:{" "}
          <EntityLink color={absorbedBy.color} onClick={() => select({ kind: "tribe", id: absorbedBy.id })}>
            {absorbedBy.name}
          </EntityLink>
          . La sua identità sopravvive nel popolo che l&apos;ha accolta.
        </p>
      )}
      {absorbed && <p className="text-muted mt-2 text-xs">Identità assorbite: {absorbed}.</p>}
      {civ.data && civ.data.successorIds.length > 0 && (
        <p className="text-muted mt-2 text-xs">
          Stati successori:{" "}
          {civ.data.successorIds.map((id) => detail.tribes.find((t) => t.id === id)?.name ?? id).join(", ")}.
        </p>
      )}
      {civ.data?.state && civ.data.state.formerNames.length > 0 && (
        <p className="text-muted mt-2 text-xs">
          Forme politiche precedenti: {civ.data.state.formerNames.join(" → ")} → {civ.data.state.name}.
        </p>
      )}
      <details className="border-line mt-3 rounded-md border px-3 py-2 text-sm">
        <summary className="cursor-pointer text-sm">Nota storica</summary>
        <p className="mt-2">{identity.description}</p>
        <p className="text-muted mt-2 text-xs">
          Contesto statico dell&apos;identità reale ({identity.periodLabel},{" "}
          {identity.geographicAssociations.join(", ")}). Non descrive questo mondo e non ne orienta la storia.
        </p>
      </details>
      {tribe.techs.length > 0 && startingTech && (
        <p className="text-muted mt-2 text-xs">
          {startingTechName}: {TECH_METHOD_LABELS.starting}, identica per tutte le civiltà.
        </p>
      )}
      <p className="text-muted mt-3 text-xs italic">{IDENTITY_DISCLAIMER}</p>
    </section>
  );
}

/**
 * A people born from a fusion in this world. Its identity is generated, never historical: the
 * section says so and lists the identities and peoples it came from.
 */
function CompositeIdentitySection({
  tribe,
  detail,
  compositeId,
}: {
  tribe: TribeDTO;
  detail: WorldDetail;
  compositeId: string;
}) {
  const { select } = useWorldUi();
  const composite = detail.composites.find((c) => c.id === compositeId)!;
  const sources = composite.sourceCivilizationIds
    .map((id) => detail.tribes.find((t) => t.id === id))
    .filter((t): t is TribeDTO => t !== undefined);
  return (
    <section aria-label="Identità composita" className="mb-2">
      <div className="mb-2 flex items-center gap-2">
        <IdentityEmblem emblemKey={composite.emblemKey} color={tribe.color} />
        <div className="min-w-0">
          <p className="text-muted text-xs">Identità composita · generata dalla simulazione</p>
          <p className="truncate font-serif text-lg leading-tight">{composite.displayName}</p>
        </div>
        <span className="ml-auto flex gap-1" aria-label="Palette">
          <span className="size-4 rounded-sm" style={{ background: composite.primaryColor }} />
          <span className="size-4 rounded-sm" style={{ background: composite.secondaryColor }} />
        </span>
      </div>
      <Facts
        items={[
          ["Nata nel", fmtYear(composite.createdYear)],
          ["Identità d'origine", composite.sourceNames.join(" + ")],
          ["Tratti culturali", composite.tags.join(", ") || "—"],
          ["Civiltà storica reale", "No"],
        ]}
      />
      {sources.length > 0 && (
        <p className="text-muted mt-2 text-xs">
          Popoli d&apos;origine:{" "}
          {sources.map((s, i) => (
            <span key={s.id}>
              {i > 0 && ", "}
              <EntityLink color={s.color} onClick={() => select({ kind: "tribe", id: s.id })}>
                {s.name}
              </EntityLink>
            </span>
          ))}
          . Restano nella cronologia come popoli confluiti nella nuova identità.
        </p>
      )}
      <p className="text-muted mt-3 text-xs italic">
        {IDENTITY_TYPE_LABELS.composite}: nome, palette e cultura sono stati generati dal motore a partire
        dalle identità d&apos;origine. Non rappresenta un popolo storico.
      </p>
    </section>
  );
}
