"use client";

import { useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { api, queryKeys } from "@/lib/client/api";
import { fmtYear, GOVERNMENT_LABELS } from "@/lib/client/format";
import {
  CIV_STATUS_LABELS,
  IDENTITY_DISCLAIMER,
  IDENTITY_TYPE_LABELS,
  TECH_METHOD_LABELS,
} from "@/lib/client/identity";
import type { TribeDTO, WorldDetail } from "@/lib/dto";
import { useWorldUi } from "@/lib/client/store";
import { IdentityEmblem } from "./identity-emblem";
import { EntityLink, Facts, SubHeading } from "./stat-bits";

/**
 * Identity of a people and the history it produced in this world. The two are kept visibly
 * apart: the identity is static flavour, everything under "Storia in questo mondo" was
 * generated by the simulation.
 */
export function TribeIdentitySection({ tribe, detail }: { tribe: TribeDTO; detail: WorldDetail }) {
  const { select } = useWorldUi();
  const worldId = detail.world.id;
  const identity = detail.identities.find((i) => i.key === tribe.identityId);
  const entry = detail.roster?.entries.find((e) => e.tribeId === tribe.id);
  // Keyed on the tick: the facts change only when the world advances.
  const civ = useQuery({
    queryKey: [...queryKeys.civilization(worldId, tribe.id), detail.world.currentTick],
    queryFn: () => api.civilization(worldId, tribe.id),
    enabled: identity !== undefined,
    staleTime: Infinity,
  });
  const absorbedBy = detail.tribes.find((t) => t.id === tribe.absorbedByTribeId);
  const parent = detail.tribes.find((t) => t.id === tribe.parentTribeId);
  const absorbed = tribe.absorbedIdentityIds
    .map((key) => detail.identities.find((i) => i.key === key)?.displayName ?? key)
    .join(", ");
  const startingTech = detail.discoveries.find((d) => d.tribeId === tribe.id && d.method === "starting");
  const startingTechName = startingTech
    ? (detail.technologies.find((t) => t.id === startingTech.techId)?.name ?? startingTech.techId)
    : null;

  if (!identity) {
    return (
      <p className="text-muted mb-3 text-xs">
        {IDENTITY_TYPE_LABELS[tribe.identityType] ?? "Popolo inventato"}: nome e storia sono interamente
        procedurali.
      </p>
    );
  }

  return (
    <section aria-label="Identità e storia" className="mb-2">
      <div className="mb-2 flex items-center gap-2">
        <IdentityEmblem emblemKey={identity.emblemKey} color={tribe.color} />
        <div className="min-w-0">
          <p className="text-muted text-xs">Identità</p>
          <p className="truncate font-serif text-lg leading-tight">{identity.displayName}</p>
        </div>
        {civ.data && (
          <Badge className="ml-auto">{CIV_STATUS_LABELS[civ.data.status] ?? civ.data.status}</Badge>
        )}
      </div>
      <SubHeading>Storia in questo mondo</SubHeading>
      <Facts
        items={[
          [
            "Fondata",
            entry ? `al tick 0 (${fmtYear(tribe.foundedYear)})` : `nel ${fmtYear(tribe.foundedYear)}`,
          ],
          [
            parent ? "Nata da" : "Origine",
            parent ? (
              <EntityLink color={parent.color} onClick={() => select({ kind: "tribe", id: parent.id })}>
                {parent.name}
              </EntityLink>
            ) : (
              "Roster di fondazione"
            ),
          ],
          ["Leader iniziale", entry?.initialLeaderName ?? "—"],
          ["Tecnologia iniziale", startingTechName ?? (parent ? "Ereditata" : "—")],
          ["Primo insediamento", civ.data?.firstSettlement?.name ?? (civ.isPending ? "…" : "Non ancora")],
          ["Governo attuale", GOVERNMENT_LABELS[tribe.government] ?? tribe.government],
          ["Storia reale applicata", "No"],
          ["Identità storica come ispirazione", "Sì"],
        ]}
      />
      {absorbedBy && (
        <p className="text-muted mt-2 text-xs">
          Assorbita da:{" "}
          <EntityLink color={absorbedBy.color} onClick={() => select({ kind: "tribe", id: absorbedBy.id })}>
            {absorbedBy.name}
          </EntityLink>
          . La sua identità sopravvive nel popolo che l&apos;ha accolta.
        </p>
      )}
      {absorbed && <p className="text-muted mt-2 text-xs">Identità assorbite: {absorbed}.</p>}
      {civ.data && civ.data.successorIds.length > 0 && (
        <p className="text-muted mt-2 text-xs">
          Stati successori:{" "}
          {civ.data.successorIds.map((id) => detail.tribes.find((t) => t.id === id)?.name ?? id).join(", ")}.
        </p>
      )}
      {civ.data?.state && civ.data.state.formerNames.length > 0 && (
        <p className="text-muted mt-2 text-xs">
          Forme politiche precedenti: {civ.data.state.formerNames.join(" → ")} → {civ.data.state.name}.
        </p>
      )}
      <details className="border-line mt-3 rounded-md border px-3 py-2 text-sm">
        <summary className="cursor-pointer text-sm">Nota storica</summary>
        <p className="mt-2">{identity.description}</p>
        <p className="text-muted mt-2 text-xs">
          Contesto statico dell&apos;identità reale ({identity.periodLabel},{" "}
          {identity.geographicAssociations.join(", ")}). Non descrive questo mondo e non ne orienta la storia.
        </p>
      </details>
      {tribe.techs.length > 0 && startingTech && (
        <p className="text-muted mt-2 text-xs">
          {startingTechName}: {TECH_METHOD_LABELS.starting}, identica per tutte le civiltà.
        </p>
      )}
      <p className="text-muted mt-3 text-xs italic">{IDENTITY_DISCLAIMER}</p>
    </section>
  );
}
