import {
  IDENTITY_CATALOG_VERSION,
  historicalIdentitySchema,
  type HistoricalIdentityDefinition,
} from "./definition";

/**
 * Catalog of the historical identities a world can use.
 *
 * Descriptions are static context about the real people and are shown as a "historical
 * note" only; nothing in them is read by the engine. Naming profiles are phonetic
 * inspirations: they produce new names, never real rulers or cities (see `reservedNames`).
 * Modifiers are tiny, balanced and switchable off (competitive mode).
 *
 * To add an identity: append an entry, keep `key` stable forever (it is persisted), pick a
 * primary colour not used yet and bump `IDENTITY_CATALOG_VERSION`. The catalog tests
 * validate every entry against `historicalIdentitySchema`.
 */
const V = IDENTITY_CATALOG_VERSION;

const RAW_CATALOG: HistoricalIdentityDefinition[] = [
  {
    key: "egyptian",
    displayName: "Egizi",
    shortName: "Egizi",
    aliases: ["Egypt", "Ancient Egyptians", "Antichi Egizi"],
    broadCategory: "ancient",
    continent: "africa",
    periodLabel: "Antichità",
    geographicAssociations: ["Valle del Nilo", "Delta del Nilo"],
    visualProfile: {
      primaryColor: "#d9a441",
      secondaryColor: "#1f6f8b",
      emblemKey: "sun",
      architecture: "pietra squadrata, tetti piani, colonne a fascio",
    },
    namingProfile: {
      starts: ["men", "ka", "nef", "hor", "set", "mer", "ne", "ta", "hen", "sen", "ptah", "wer"],
      middles: ["ka", "ne", "mu", "ru", "hot", "ib"],
      middleChance: 0.35,
      ends: ["ka", "ef", "ra", "et", "mes", "hu", "nu", "ib"],
      feminineEnds: ["et", "ra", "it", "enet", "ya"],
      placeEnds: ["naru", "set", "kem", "wast", "hut", "ib"],
      placePrefixes: ["Per-", "Ta-"],
      placeSuffixes: [],
      reservedNames: [
        "Ramses",
        "Ramesse",
        "Menes",
        "Narmer",
        "Cheope",
        "Khufu",
        "Khafra",
        "Djoser",
        "Hatshepsut",
        "Akhenaton",
        "Nefertiti",
        "Cleopatra",
        "Tutankhamon",
        "Kemet",
        "Tebe",
        "Menfi",
        "Waset",
      ],
    },
    culturalTags: ["riverine", "architectural", "agrarian_potential"],
    behavioralModifiers: [
      {
        id: "river_order",
        trait: "centralization",
        value: 4,
        tradeoff: "Meno spinta a espandersi lontano dalla propria terra",
      },
      { id: "rooted", trait: "expansionism", value: -4, tradeoff: "Compensa l'inclinazione all'ordine" },
    ],
    description:
      "Popolo dell'Africa nordorientale la cui civiltà storica si sviluppò lungo il Nilo per circa tre millenni, nota per l'architettura monumentale, la scrittura geroglifica e un'amministrazione legata alle piene del fiume.",
    representationNotes:
      "In Genesis gli Egizi partono come un clan qualsiasi: niente Nilo garantito, niente faraoni, niente piramidi. Solo nome, palette e sonorità dei nomi richiamano la tradizione.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "ancient Egypt" }],
    dataVersion: V,
  },
  {
    key: "sumerian",
    displayName: "Sumeri",
    shortName: "Sumeri",
    aliases: ["Sumerians", "Sumer"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Mesopotamia meridionale"],
    visualProfile: {
      primaryColor: "#b5651d",
      secondaryColor: "#e8d5a3",
      emblemKey: "star",
      architecture: "mattoni crudi, terrazze a gradoni, cortili",
    },
    namingProfile: {
      starts: ["en", "lu", "ur", "nin", "gil", "shul", "an", "ku", "dum", "ug", "zi", "mes"],
      middles: ["ba", "ga", "an", "zi", "gal", "du"],
      middleChance: 0.4,
      ends: ["gal", "ki", "ma", "zu", "dug", "ra", "na"],
      feminineEnds: ["na", "ki", "ma", "ru"],
      placeEnds: ["uk", "ki", "du", "gash", "ab", "er"],
      placePrefixes: ["E-"],
      placeSuffixes: ["-ki"],
      reservedNames: [
        "Gilgamesh",
        "Ur",
        "Uruk",
        "Lagash",
        "Eridu",
        "Sargon",
        "Enheduanna",
        "Ur-Nammu",
        "Shulgi",
      ],
    },
    culturalTags: ["riverine", "urban_potential", "record_keeping"],
    behavioralModifiers: [
      { id: "tinkerers", trait: "innovation", value: 3, tradeoff: "Più litigiosi con i vicini" },
      { id: "city_rivalry", trait: "cooperation", value: -3, tradeoff: "Compensa la curiosità tecnica" },
    ],
    description:
      "Abitanti storici della Mesopotamia meridionale, tra i primi a sviluppare città-stato, la scrittura cuneiforme e sistemi di irrigazione su larga scala.",
    representationNotes:
      "Nessuna scrittura o irrigazione iniziale: i Sumeri di Genesis devono inventare tutto come gli altri. L'identità fornisce solo nome, colori e sonorità.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Sumer" }],
    dataVersion: V,
  },
  {
    key: "babylonian",
    displayName: "Babilonesi",
    shortName: "Babilonesi",
    aliases: ["Babylonians", "Babylonia"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Mesopotamia centrale"],
    visualProfile: {
      primaryColor: "#2f5d9e",
      secondaryColor: "#e0b64c",
      emblemKey: "tower",
      architecture: "mattoni smaltati, porte ad arco, torri a gradoni",
    },
    namingProfile: {
      starts: ["mar", "nab", "sin", "ish", "ad", "bel", "sham", "ib", "na", "ku", "ea", "ze"],
      middles: ["bu", "du", "na", "ri", "ki", "tum"],
      middleChance: 0.45,
      ends: ["ukin", "idin", "nu", "ri", "bal", "ish", "um"],
      feminineEnds: ["tum", "tu", "ati", "ia"],
      placeEnds: ["il", "ar", "ab", "ish", "ira", "ur"],
      placePrefixes: ["Dur-", "Kar-"],
      placeSuffixes: [],
      reservedNames: [
        "Hammurabi",
        "Nabucodonosor",
        "Nebuchadnezzar",
        "Babilonia",
        "Babel",
        "Marduk",
        "Ishtar",
      ],
    },
    culturalTags: ["riverine", "legalistic", "astronomical"],
    behavioralModifiers: [
      { id: "code_minded", trait: "centralization", value: 3, tradeoff: "Commerci più cauti" },
      {
        id: "guarded_markets",
        trait: "tradeOpenness",
        value: -3,
        tradeoff: "Compensa l'inclinazione alle regole",
      },
    ],
    description:
      "Popolo mesopotamico legato alla città di Babilonia, ricordato per la raccolta di leggi scritte, l'astronomia e un ruolo centrale nella storia del Vicino Oriente antico.",
    representationNotes:
      "Nessun codice di leggi precostituito: le leggi, se arriveranno, saranno una scoperta della simulazione. Il nome della città storica è escluso dai nomi generati.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Babylonia" }],
    dataVersion: V,
  },
  {
    key: "assyrian",
    displayName: "Assiri",
    shortName: "Assiri",
    aliases: ["Assyrians", "Assyria"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Alto Tigri"],
    visualProfile: {
      primaryColor: "#8c2f39",
      secondaryColor: "#d9c49a",
      emblemKey: "eye",
      architecture: "palazzi su terrapieni, bassorilievi, porte monumentali",
    },
    namingProfile: {
      starts: ["ash", "tig", "sal", "sen", "adad", "nin", "ur", "ki", "ar", "bel", "ta", "shu"],
      middles: ["ur", "na", "pil", "ba", "ri", "me"],
      middleChance: 0.45,
      ends: ["ur", "ser", "nu", "pal", "ib", "ri"],
      feminineEnds: ["tu", "ia", "ati", "ra"],
      placeEnds: ["ur", "ud", "ib", "al", "esh", "ki"],
      placePrefixes: ["Kar-"],
      placeSuffixes: [],
      reservedNames: [
        "Ninive",
        "Nineveh",
        "Assur",
        "Ashur",
        "Sennacherib",
        "Assurbanipal",
        "Sargon",
        "Semiramide",
        "Nimrud",
      ],
    },
    culturalTags: ["upland", "archival", "monumental"],
    behavioralModifiers: [
      {
        id: "archive_keepers",
        trait: "centralization",
        value: 3,
        tradeoff: "Minore spirito di collaborazione",
      },
      { id: "stern_hierarchy", trait: "cooperation", value: -3, tradeoff: "Compensa la centralizzazione" },
    ],
    description:
      "Popolo della Mesopotamia settentrionale che diede vita a una lunga serie di stati attorno alla città di Assur, noti per archivi, biblioteche e un'imponente arte palatina.",
    representationNotes:
      "La storiografia tende a ridurre gli Assiri alla guerra: qui nessun bonus militare, solo una leggera inclinazione all'organizzazione controbilanciata.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Assyria" }],
    dataVersion: V,
  },
  {
    key: "persian",
    displayName: "Persiani",
    shortName: "Persiani",
    aliases: ["Persians", "Iranians", "Persia"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Altopiano iranico"],
    visualProfile: {
      primaryColor: "#5b3f8c",
      secondaryColor: "#d4af37",
      emblemKey: "feather",
      architecture: "sale ipostile, giardini recintati, colonne con capitelli animali",
    },
    namingProfile: {
      starts: ["dar", "ar", "khsha", "mith", "far", "bar", "vah", "ros", "par", "zar", "ho", "shah"],
      middles: ["ya", "ta", "ra", "va", "ma", "na"],
      middleChance: 0.4,
      ends: ["es", "ab", "ush", "an", "ar", "dad", "zad"],
      feminineEnds: ["a", "ane", "ina", "ta"],
      placeEnds: ["abad", "gerd", "an", "ar", "sa", "vand"],
      placePrefixes: [],
      placeSuffixes: ["-dan"],
      reservedNames: [
        "Ciro",
        "Cyrus",
        "Dario",
        "Darius",
        "Serse",
        "Xerxes",
        "Persepoli",
        "Persepolis",
        "Pasargade",
        "Susa",
      ],
    },
    culturalTags: ["upland", "road_builders", "pluralist"],
    behavioralModifiers: [
      { id: "tolerant_rule", trait: "cooperation", value: 3, tradeoff: "Meno inclinati al conflitto armato" },
      { id: "measured_force", trait: "militarism", value: -3, tradeoff: "Compensa l'apertura" },
    ],
    description:
      "Popoli di lingua iranica dell'altopiano omonimo, associati storicamente a grandi imperi multietnici, a una rete stradale estesa e a un'amministrazione per satrapie.",
    representationNotes:
      "Nessun impero di partenza e nessuna rete stradale: la tolleranza è una lieve inclinazione iniziale che la storia del mondo può cancellare.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "ancient Iran" }],
    dataVersion: V,
  },
  {
    key: "phoenician",
    displayName: "Fenici",
    shortName: "Fenici",
    aliases: ["Phoenicians", "Phoenicia", "Canaanites"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Costa del Levante"],
    visualProfile: {
      primaryColor: "#7b1e5a",
      secondaryColor: "#f2e6c9",
      emblemKey: "ship",
      architecture: "porti in pietra, case a più piani, magazzini portuali",
    },
    namingProfile: {
      starts: ["abd", "bod", "hi", "ma", "ela", "yat", "shi", "ba", "gad", "ah", "tab", "esh"],
      middles: ["ba", "mil", "ram", "ta", "ka", "ne"],
      middleChance: 0.4,
      ends: ["bal", "art", "on", "ram", "ek", "im"],
      feminineEnds: ["at", "et", "sa", "ah"],
      placeEnds: ["on", "os", "ad", "ut", "ar", "im"],
      placePrefixes: ["Qart-"],
      placeSuffixes: [],
      reservedNames: [
        "Tiro",
        "Tyre",
        "Sidone",
        "Sidon",
        "Biblo",
        "Byblos",
        "Hiram",
        "Didone",
        "Elissa",
        "Qart-Hadasht",
      ],
    },
    culturalTags: ["maritime", "mercantile", "alphabetic"],
    behavioralModifiers: [
      {
        id: "harbour_minded",
        trait: "tradeOpenness",
        value: 4,
        tradeoff: "Poco interesse per il controllo del territorio",
      },
      { id: "light_hold", trait: "centralization", value: -4, tradeoff: "Compensa l'apertura commerciale" },
    ],
    description:
      "Popolo di città costiere del Levante celebre per il commercio marittimo, la porpora e la diffusione di un alfabeto consonantico nel Mediterraneo.",
    representationNotes:
      "Nessuna navigazione iniziale e nessuna costa garantita: un'eventuale vocazione marittima dipenderà dalla mappa.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Phoenicia" }],
    dataVersion: V,
  },
  {
    key: "greek",
    displayName: "Greci",
    shortName: "Greci",
    aliases: ["Greeks", "Hellenes", "Elleni"],
    broadCategory: "classical",
    continent: "europe",
    periodLabel: "Età classica",
    geographicAssociations: ["Egeo", "Penisola balcanica meridionale"],
    visualProfile: {
      primaryColor: "#2a7fbf",
      secondaryColor: "#f5f1e6",
      emblemKey: "leaf",
      architecture: "templi colonnati, agorà, teatri all'aperto",
    },
    namingProfile: {
      starts: ["kal", "the", "ar", "eu", "phi", "de", "nik", "ly", "a", "pol", "sto", "me"],
      middles: ["lo", "ro", "ne", "da", "ki", "mo"],
      middleChance: 0.55,
      ends: ["os", "as", "on", "ias", "es", "eus"],
      feminineEnds: ["e", "a", "is", "eia", "ne"],
      placeEnds: ["os", "a", "ai", "ion", "is", "ene"],
      placePrefixes: [],
      placeSuffixes: ["polis"],
      reservedNames: [
        "Pericle",
        "Pericles",
        "Alessandro",
        "Alexandros",
        "Leonida",
        "Atene",
        "Athenai",
        "Sparta",
        "Corinto",
        "Omero",
        "Socrate",
        "Platone",
        "Solone",
      ],
    },
    culturalTags: ["maritime", "civic", "philosophical"],
    behavioralModifiers: [
      { id: "debaters", trait: "innovation", value: 3, tradeoff: "Autorità centrale più debole" },
      { id: "fractious", trait: "centralization", value: -3, tradeoff: "Compensa la curiosità" },
    ],
    description:
      "Popoli di lingua greca dell'Egeo, organizzati storicamente in numerose poleis indipendenti e ricordati per la filosofia, il teatro e le istituzioni civiche.",
    representationNotes:
      "Nessuna polis, democrazia o filosofia di partenza: se i Greci di un mondo diventeranno una repubblica sarà per le vicende del mondo.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "ancient Greek civilization" }],
    dataVersion: V,
  },
  {
    key: "roman",
    displayName: "Romani",
    shortName: "Romani",
    aliases: ["Romans", "Rome", "Antichi Romani"],
    broadCategory: "classical",
    continent: "europe",
    periodLabel: "Età classica",
    geographicAssociations: ["Italia centrale", "Lazio"],
    visualProfile: {
      primaryColor: "#a4262c",
      secondaryColor: "#e3c16f",
      emblemKey: "shield",
      architecture: "archi, volte, strade lastricate, fori",
    },
    namingProfile: {
      starts: ["mar", "lu", "gai", "ti", "qui", "sex", "pu", "ser", "ap", "ful", "cor", "vale"],
      middles: ["ci", "li", "ri", "ni", "ti", "bi"],
      middleChance: 0.45,
      ends: ["us", "ius", "o", "anus", "ens"],
      feminineEnds: ["a", "ia", "ina", "illa"],
      placeEnds: ["um", "ia", "ae", "ium", "ona", "ano"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Romolo",
        "Romulus",
        "Remo",
        "Cesare",
        "Caesar",
        "Augusto",
        "Augustus",
        "Nerone",
        "Roma",
        "Traiano",
        "Cicerone",
        "Scipione",
      ],
    },
    culturalTags: ["civic", "engineering_potential", "legal"],
    behavioralModifiers: [
      { id: "roadminded", trait: "expansionism", value: 3, tradeoff: "Minore propensione all'innovazione" },
      { id: "custom_bound", trait: "innovation", value: -3, tradeoff: "Compensa la spinta espansiva" },
    ],
    description:
      "Popolo dell'Italia centrale la cui città diede nome a una repubblica e poi a un impero mediterraneo, ricordato per il diritto, l'ingegneria e le infrastrutture.",
    representationNotes:
      "Nessuna ingegneria automatica, nessuna Roma e nessun impero: strade e acquedotti andranno scoperti e costruiti come per chiunque altro.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "ancient Rome" }],
    dataVersion: V,
  },
  {
    key: "carthaginian",
    displayName: "Cartaginesi",
    shortName: "Cartaginesi",
    aliases: ["Carthaginians", "Punici", "Carthage"],
    broadCategory: "classical",
    continent: "africa",
    periodLabel: "Età classica",
    geographicAssociations: ["Africa settentrionale", "Mediterraneo occidentale"],
    visualProfile: {
      primaryColor: "#6a2c70",
      secondaryColor: "#f6c85f",
      emblemKey: "moon",
      architecture: "porti circolari, case a cortile, mura su istmo",
    },
    namingProfile: {
      starts: ["ha", "has", "bo", "ma", "gis", "him", "sa", "bal", "adh", "ak", "mut", "ish"],
      middles: ["mil", "dru", "ba", "go", "ni", "ka"],
      middleChance: 0.4,
      ends: ["bal", "car", "on", "go", "ar", "bal"],
      feminineEnds: ["at", "ba", "et", "na"],
      placeEnds: ["ut", "a", "on", "ek", "ar", "is"],
      placePrefixes: ["Qart-"],
      placeSuffixes: [],
      reservedNames: [
        "Annibale",
        "Hannibal",
        "Amilcare",
        "Hamilcar",
        "Asdrubale",
        "Hasdrubal",
        "Cartagine",
        "Carthago",
        "Didone",
        "Magone",
      ],
    },
    culturalTags: ["maritime", "mercantile", "oligarchic"],
    behavioralModifiers: [
      { id: "merchant_houses", trait: "tradeOpenness", value: 3, tradeoff: "Meno coesione interna" },
      {
        id: "faction_split",
        trait: "cooperation",
        value: -3,
        tradeoff: "Compensa l'orientamento mercantile",
      },
    ],
    description:
      "Popolo di origine fenicia stabilitosi in Africa settentrionale, con una potente città mercantile che dominò a lungo le rotte del Mediterraneo occidentale.",
    representationNotes:
      "Il conflitto storico con Roma non viene riprodotto: in Genesis Romani e Cartaginesi, se presenti, non hanno relazioni predefinite.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Carthage" }],
    dataVersion: V,
  },
  {
    key: "celtic",
    displayName: "Celti",
    shortName: "Celti",
    aliases: ["Celts", "Gauls", "Galli"],
    broadCategory: "ancient",
    continent: "europe",
    periodLabel: "Età del Ferro",
    geographicAssociations: ["Europa centrale e occidentale"],
    visualProfile: {
      primaryColor: "#2e8b57",
      secondaryColor: "#c9a227",
      emblemKey: "spiral",
      architecture: "case rotonde, oppida su alture, recinti di legno",
    },
    namingProfile: {
      starts: ["bren", "ver", "cun", "brig", "tar", "dum", "cat", "ogm", "lug", "e", "mor", "ar"],
      middles: ["no", "ro", "ci", "ta", "ve", "lo"],
      middleChance: 0.4,
      ends: ["ix", "os", "ac", "rix", "an", "ed"],
      feminineEnds: ["a", "id", "wen", "is"],
      placeEnds: ["dun", "mag", "briga", "acum", "ium", "dur"],
      placePrefixes: [],
      placeSuffixes: ["-dunum"],
      reservedNames: [
        "Vercingetorige",
        "Vercingetorix",
        "Boudicca",
        "Brenno",
        "Brennus",
        "Alesia",
        "Bibracte",
      ],
    },
    culturalTags: ["forest", "confederal", "artisanal"],
    behavioralModifiers: [
      { id: "wanderers", trait: "expansionism", value: 3, tradeoff: "Potere centrale più debole" },
      { id: "many_chiefs", trait: "centralization", value: -3, tradeoff: "Compensa la spinta migratoria" },
    ],
    description:
      "Insieme di popoli di lingua celtica diffusi dall'Europa centrale alla penisola iberica e alle isole britanniche, noti per l'arte metallurgica e gli insediamenti fortificati d'altura.",
    representationNotes:
      "“Celti” è un'etichetta moderna per popoli molto diversi tra loro: qui indica un'identità culturale ampia, non un unico stato.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Celt" }],
    dataVersion: V,
  },
  {
    key: "nubian",
    displayName: "Nubiani",
    shortName: "Nubiani",
    aliases: ["Nubians", "Kushites", "Kush", "Kushiti"],
    broadCategory: "ancient",
    continent: "africa",
    periodLabel: "Antichità",
    geographicAssociations: ["Medio Nilo", "Nubia"],
    visualProfile: {
      primaryColor: "#c1440e",
      secondaryColor: "#f0d9a8",
      emblemKey: "landmark",
      architecture: "templi in arenaria, piramidi slanciate, capanne rotonde",
    },
    namingProfile: {
      starts: ["ar", "ta", "na", "ka", "pi", "shab", "am", "ne", "ma", "sha", "kan", "ab"],
      middles: ["ha", "ma", "ta", "ni", "ka", "ra"],
      middleChance: 0.4,
      ends: ["kal", "ye", "ra", "ta", "ni", "amani"],
      feminineEnds: ["ke", "ti", "ra", "tore"],
      placeEnds: ["oe", "ta", "ka", "at", "ma", "ra"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: ["Piye", "Taharqa", "Kashta", "Shabaka", "Meroe", "Napata", "Kerma", "Amanirenas"],
    },
    culturalTags: ["riverine", "pastoral", "monumental"],
    behavioralModifiers: [
      { id: "herders", trait: "expansionism", value: 3, tradeoff: "Commercio meno sviluppato" },
      { id: "self_reliant", trait: "tradeOpenness", value: -3, tradeoff: "Compensa la mobilità" },
    ],
    description:
      "Popoli della valle del medio Nilo che diedero vita ai regni di Kerma e di Kush, per un periodo dominanti anche sull'Egitto, con una propria tradizione di piramidi e scrittura meroitica.",
    representationNotes:
      "L'identità include la tradizione kushita. I Nubiani non sono presentati come appendice degli Egizi: sono un'identità autonoma e con pari condizioni.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Nubia" }],
    dataVersion: V,
  },
  {
    key: "chinese",
    displayName: "Cinesi",
    shortName: "Cinesi",
    aliases: ["Chinese", "Han", "Zhongguo"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Valle del Fiume Giallo", "Valle dello Yangtze"],
    visualProfile: {
      primaryColor: "#c8102e",
      secondaryColor: "#f4c430",
      emblemKey: "serpent",
      architecture: "terrapieni di terra battuta, tetti in legno a sbalzo, cortili",
    },
    namingProfile: {
      starts: ["li", "wen", "zhao", "chen", "ming", "jun", "xi", "hua", "lan", "yu", "shen", "bo"],
      middles: ["an", "yi", "ze", "lo", "ren", "he"],
      middleChance: 0.3,
      ends: ["", "an", "ong", "ei", "ao", "ing"],
      feminineEnds: ["ya", "lan", "mei", "hua", "yu"],
      placeEnds: ["yang", "an", "zhou", "ling", "du", "shan"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Qin",
        "Shi Huang",
        "Huangdi",
        "Kongzi",
        "Confucio",
        "Laozi",
        "Xianyang",
        "Chang'an",
        "Changan",
        "Luoyang",
        "Anyang",
      ],
    },
    culturalTags: ["riverine", "agrarian_potential", "bureaucratic_potential"],
    behavioralModifiers: [
      { id: "kin_networks", trait: "cooperation", value: 3, tradeoff: "Meno inclini ad allargarsi" },
      { id: "home_valley", trait: "expansionism", value: -3, tradeoff: "Compensa la coesione" },
    ],
    description:
      "Popoli delle grandi valli fluviali della Cina, le cui culture neolitiche e dell'età del bronzo diedero origine a una lunga tradizione statale, scritta e agricola.",
    representationNotes:
      "Nessuna dinastia, burocrazia o scrittura di partenza. L'identità riunisce in modo semplificato tradizioni regionali molto diverse.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "China — history" }],
    dataVersion: V,
  },
  {
    key: "indian",
    displayName: "Indiani",
    shortName: "Indiani",
    aliases: ["Indians", "Indus peoples", "Bharata"],
    broadCategory: "ancient",
    continent: "asia",
    periodLabel: "Antichità",
    geographicAssociations: ["Valle dell'Indo", "Pianura del Gange"],
    visualProfile: {
      primaryColor: "#ff9933",
      secondaryColor: "#138808",
      emblemKey: "wheat",
      architecture: "mattoni cotti, città a griglia, bacini d'acqua",
    },
    namingProfile: {
      starts: ["ra", "de", "vi", "su", "an", "ka", "ma", "pra", "cha", "a", "go", "ha"],
      middles: ["ja", "ni", "ra", "ma", "va", "sha"],
      middleChance: 0.5,
      ends: ["an", "ya", "esh", "ar", "it", "und"],
      feminineEnds: ["i", "a", "ika", "ini", "ita"],
      placeEnds: ["pur", "abad", "garh", "nagar", "ali", "ra"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Ashoka",
        "Chandragupta",
        "Harappa",
        "Mohenjo-daro",
        "Pataliputra",
        "Buddha",
        "Siddharta",
        "Gandhi",
      ],
    },
    culturalTags: ["riverine", "urban_potential", "plural"],
    behavioralModifiers: [
      { id: "exchange_webs", trait: "tradeOpenness", value: 3, tradeoff: "Meno orientati alla guerra" },
      { id: "peace_leaning", trait: "militarism", value: -3, tradeoff: "Compensa l'apertura" },
    ],
    description:
      "Popoli del subcontinente indiano, dalla civiltà urbana della valle dell'Indo ai regni della pianura del Gange, con una grande varietà di lingue, religioni e tradizioni.",
    representationNotes:
      "Un'unica etichetta per una realtà molto plurale: nel gioco è un'identità culturale ampia, non una nazione moderna né una singola epoca.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Indus civilization" }],
    dataVersion: V,
  },
  {
    key: "minoan",
    displayName: "Minoici",
    shortName: "Minoici",
    aliases: ["Minoans", "Cretesi dell'età del bronzo"],
    broadCategory: "ancient",
    continent: "europe",
    periodLabel: "Età del Bronzo",
    geographicAssociations: ["Creta", "Egeo meridionale"],
    visualProfile: {
      primaryColor: "#e07a5f",
      secondaryColor: "#3d9ec2",
      emblemKey: "wave",
      architecture: "palazzi a cortile centrale, colonne rastremate, affreschi",
    },
    namingProfile: {
      starts: ["ka", "pa", "ta", "da", "ku", "mi", "ra", "sa", "i", "ne", "a", "tu"],
      middles: ["ru", "ni", "na", "sa", "da", "ja"],
      middleChance: 0.5,
      ends: ["tos", "sos", "ra", "na", "tho", "ro"],
      feminineEnds: ["ja", "na", "ta", "ri"],
      placeEnds: ["nos", "sos", "tos", "ra", "tho", "nda"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Minosse",
        "Minos",
        "Cnosso",
        "Knossos",
        "Festo",
        "Phaistos",
        "Arianna",
        "Malia",
        "Zakros",
      ],
    },
    culturalTags: ["maritime", "palatial", "artistic"],
    behavioralModifiers: [
      { id: "island_calm", trait: "cooperation", value: 3, tradeoff: "Difese e armi trascurate" },
      { id: "unwalled", trait: "militarism", value: -3, tradeoff: "Compensa la cooperazione" },
    ],
    description:
      "Civiltà dell'età del bronzo di Creta, nota per i complessi palaziali, gli affreschi e una scrittura (Lineare A) ancora non decifrata.",
    representationNotes:
      "Il nome “Minoici” è una convenzione moderna: non sappiamo come si chiamassero. Le sonorità dei nomi generati sono pura invenzione.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Minoan civilization" }],
    dataVersion: V,
  },
  {
    key: "maya",
    displayName: "Maya",
    shortName: "Maya",
    aliases: ["Maya", "Mayans", "Maya peoples"],
    broadCategory: "indigenous",
    continent: "americas",
    periodLabel: "Epoca precolombiana",
    geographicAssociations: ["Penisola dello Yucatán", "Altopiani del Guatemala"],
    visualProfile: {
      primaryColor: "#1b998b",
      secondaryColor: "#e9c46a",
      emblemKey: "bird",
      architecture: "piramidi a gradoni, piazze cerimoniali, stele",
    },
    namingProfile: {
      starts: ["k'", "yax", "ix", "bah", "chak", "kan", "ahk", "tun", "hun", "itz", "uk", "bal"],
      middles: ["in", "ah", "ul", "ek", "am", "ich"],
      middleChance: 0.5,
      ends: ["ul", "ahk", "in", "ek", "am", "nal"],
      feminineEnds: ["ix", "ul", "ah", "ek"],
      placeEnds: ["tun", "ha", "nal", "ul", "kab", "che"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Pakal",
        "K'inich",
        "Tikal",
        "Palenque",
        "Copán",
        "Copan",
        "Calakmul",
        "Chichén",
        "Uxmal",
      ],
    },
    culturalTags: ["forest", "astronomical", "city_network"],
    behavioralModifiers: [
      { id: "sky_watchers", trait: "innovation", value: 3, tradeoff: "Città più divise" },
      { id: "city_networks", trait: "centralization", value: -3, tradeoff: "Compensa la curiosità" },
    ],
    description:
      "Popoli della Mesoamerica sudorientale, organizzati storicamente in città-stato con una scrittura logosillabica, un calendario raffinato e grandi centri cerimoniali. Le comunità maya esistono ancora oggi.",
    representationNotes:
      "Nessuna matematica o calendario automatico. I Maya sono un popolo vivente: il gioco usa l'identità storica con rispetto, senza rappresentare le comunità odierne.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Maya" }],
    dataVersion: V,
  },
  {
    key: "mexica",
    displayName: "Mexica",
    shortName: "Mexica",
    aliases: ["Aztechi", "Aztecs", "Mexica"],
    broadCategory: "indigenous",
    continent: "americas",
    periodLabel: "Epoca precolombiana",
    geographicAssociations: ["Valle del Messico"],
    visualProfile: {
      primaryColor: "#0f7173",
      secondaryColor: "#f07167",
      emblemKey: "flame",
      architecture: "templi gemelli, chinampas, canali e argini",
    },
    namingProfile: {
      starts: ["cuauh", "ix", "tla", "xo", "ome", "a", "toch", "mix", "ya", "ci", "qua", "chi"],
      middles: ["tla", "co", "hua", "pil", "me", "ton"],
      middleChance: 0.5,
      ends: ["tli", "atl", "co", "tzin", "itl", "pan"],
      feminineEnds: ["chitl", "tzin", "atl", "ci"],
      placeEnds: ["tlan", "co", "pan", "can", "apan", "yan"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Moctezuma",
        "Montezuma",
        "Cuauhtémoc",
        "Cuauhtemoc",
        "Tenochtitlan",
        "Tlatelolco",
        "Texcoco",
        "Tlacaelel",
        "Itzcoatl",
      ],
    },
    culturalTags: ["lacustrine", "tributary", "agrarian_potential"],
    behavioralModifiers: [
      { id: "lake_farmers", trait: "cooperation", value: 3, tradeoff: "Scambi a lunga distanza più rari" },
      { id: "tribute_minded", trait: "tradeOpenness", value: -3, tradeoff: "Compensa la cooperazione" },
    ],
    description:
      "Popolo di lingua nahuatl stabilitosi nella valle del Messico, noto per le città lacustri, i campi galleggianti (chinampas) e una vasta rete tributaria.",
    representationNotes:
      "“Aztechi” è il nome più diffuso, “Mexica” il nome che il popolo usava. Nessuna guerra rituale o sacrificio è modellato: sarebbe solo uno stereotipo.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Aztec" }],
    dataVersion: V,
  },
  {
    key: "inca",
    displayName: "Inca",
    shortName: "Inca",
    aliases: ["Incas", "Tawantinsuyu", "Quechua"],
    broadCategory: "indigenous",
    continent: "americas",
    periodLabel: "Epoca precolombiana",
    geographicAssociations: ["Ande"],
    visualProfile: {
      primaryColor: "#e76f51",
      secondaryColor: "#264653",
      emblemKey: "mountain",
      architecture: "muri a secco poligonali, terrazzamenti, magazzini",
    },
    namingProfile: {
      starts: ["pa", "wa", "tu", "ma", "ata", "yu", "ku", "chaw", "wi", "qo", "ro", "sin"],
      middles: ["ka", "ya", "chi", "pa", "ri", "ma"],
      middleChance: 0.45,
      ends: ["ku", "q", "llu", "pa", "chi", "yu"],
      feminineEnds: ["lla", "ya", "ku", "wa"],
      placeEnds: ["pampa", "marka", "qocha", "pata", "llaqta", "wasi"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: ["Pachacuti", "Atahualpa", "Huayna", "Manco", "Cusco", "Cuzco", "Machu Picchu", "Tupac"],
    },
    culturalTags: ["highland", "terracing", "redistributive"],
    behavioralModifiers: [
      { id: "storehouse_order", trait: "centralization", value: 4, tradeoff: "Meno commercio privato" },
      { id: "redistribution", trait: "tradeOpenness", value: -4, tradeoff: "Compensa l'organizzazione" },
    ],
    description:
      "Popolo andino di lingua quechua che nel XV secolo costruì il più esteso stato dell'America precolombiana, con strade montane, terrazzamenti e un sistema di magazzini e registrazione a nodi (quipu).",
    representationNotes:
      "Nessuna metallurgia o strada di partenza. I discendenti delle popolazioni andine esistono tuttora: l'identità è ispirazione, non rappresentazione.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Inca" }],
    dataVersion: V,
  },
  {
    key: "japanese",
    displayName: "Giapponesi",
    shortName: "Giapponesi",
    aliases: ["Japanese", "Yamato", "Nihon"],
    broadCategory: "medieval",
    continent: "asia",
    periodLabel: "Età antica e medievale",
    geographicAssociations: ["Arcipelago giapponese"],
    visualProfile: {
      primaryColor: "#bc002d",
      secondaryColor: "#f7f7f2",
      emblemKey: "crown",
      architecture: "legno su pali, tetti curvi, recinti sacri",
    },
    namingProfile: {
      starts: ["hi", "ta", "ka", "mi", "yo", "sa", "ki", "ha", "na", "o", "ri", "to"],
      middles: ["ro", "ka", "shi", "ya", "no", "mu"],
      middleChance: 0.55,
      ends: ["ro", "shi", "ta", "ki", "masa", "o"],
      feminineEnds: ["ko", "mi", "e", "ka", "na"],
      placeEnds: ["zaki", "hara", "yama", "kawa", "shima", "no"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: ["Himiko", "Jimmu", "Nara", "Kyoto", "Heian", "Edo", "Nobunaga", "Tokugawa", "Yamato"],
    },
    culturalTags: ["island", "forest", "craft"],
    behavioralModifiers: [
      { id: "craft_care", trait: "innovation", value: 3, tradeoff: "Minore interesse per terre lontane" },
      { id: "island_home", trait: "expansionism", value: -3, tradeoff: "Compensa la cura artigianale" },
    ],
    description:
      "Popolo dell'arcipelago giapponese, le cui prime formazioni statali (Yamato) si svilupparono tra il III e il VII secolo con influenze continentali reinterpretate localmente.",
    representationNotes:
      "Niente samurai, shogun o isolamento predefinito: il gioco non conosce la storia giapponese oltre al nome e alle sonorità.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Japan — history" }],
    dataVersion: V,
  },
  {
    key: "korean",
    displayName: "Coreani",
    shortName: "Coreani",
    aliases: ["Koreans", "Goguryeo", "Silla", "Baekje"],
    broadCategory: "medieval",
    continent: "asia",
    periodLabel: "Età antica e medievale",
    geographicAssociations: ["Penisola coreana"],
    visualProfile: {
      primaryColor: "#003478",
      secondaryColor: "#cd2e3a",
      emblemKey: "tree",
      architecture: "fortezze di montagna, tetti in tegole, pavimenti riscaldati",
    },
    namingProfile: {
      starts: ["min", "ji", "seo", "hyun", "sun", "yeong", "dong", "chul", "hae", "jae", "eun", "tae"],
      middles: ["ho", "yun", "ha", "su", "jin", "woo"],
      middleChance: 0.5,
      ends: ["ho", "su", "woo", "jun", "gi", "seok"],
      feminineEnds: ["hee", "a", "yeon", "mi", "jin"],
      placeEnds: ["seong", "ju", "san", "chon", "gang", "do"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: ["Dangun", "Jumong", "Gyeongju", "Pyongyang", "Hanseong", "Sejong", "Gwanggaeto"],
    },
    culturalTags: ["upland", "fortified", "scholarly"],
    behavioralModifiers: [
      {
        id: "hill_forts",
        trait: "cooperation",
        value: 3,
        tradeoff: "Minore propensione al rischio espansivo",
      },
      { id: "guarded_valleys", trait: "expansionism", value: -3, tradeoff: "Compensa la coesione" },
    ],
    description:
      "Popoli della penisola coreana, dai regni antichi di Goguryeo, Baekje e Silla alle dinastie successive, con una propria tradizione di fortezze montane, ceramica e scrittura.",
    representationNotes:
      "Nessun regno di partenza. L'identità non riproduce divisioni moderne né rivalità storiche con i vicini.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Korea — history" }],
    dataVersion: V,
  },
  {
    key: "norse",
    displayName: "Norreni",
    shortName: "Norreni",
    aliases: ["Vichinghi", "Norse", "Vikings", "Scandinavi"],
    broadCategory: "medieval",
    continent: "europe",
    periodLabel: "Alto Medioevo",
    geographicAssociations: ["Scandinavia", "Mare del Nord"],
    visualProfile: {
      primaryColor: "#4a6fa5",
      secondaryColor: "#d8dee9",
      emblemKey: "anchor",
      architecture: "case lunghe in legno, tetti erbosi, rimesse per barche",
    },
    namingProfile: {
      starts: ["ei", "thor", "sig", "hal", "ul", "bjor", "as", "ing", "ragn", "arn", "gud", "sven"],
      middles: ["ri", "va", "ul", "mun", "ge", "stein"],
      middleChance: 0.35,
      ends: ["ulf", "ald", "ir", "var", "mund", "stein"],
      feminineEnds: ["hild", "rid", "run", "dis", "a"],
      placeEnds: ["vik", "by", "heim", "stad", "fjord", "holm"],
      placePrefixes: [],
      placeSuffixes: [],
      reservedNames: [
        "Ragnar",
        "Harald",
        "Leif",
        "Erik",
        "Canuto",
        "Knut",
        "Olaf",
        "Hedeby",
        "Birka",
        "Kaupang",
      ],
    },
    culturalTags: ["maritime", "boreal", "assembly_based"],
    behavioralModifiers: [
      { id: "far_sailing", trait: "expansionism", value: 3, tradeoff: "Autorità centrale più fragile" },
      { id: "assembly_law", trait: "centralization", value: -3, tradeoff: "Compensa la spinta esplorativa" },
    ],
    description:
      "Popoli di lingua norrena della Scandinavia altomedievale, navigatori, mercanti e coloni dall'Atlantico settentrionale al Volga, organizzati in assemblee locali (thing).",
    representationNotes:
      "“Vichinghi” indicava un'attività, non un popolo: qui si usa “Norreni”. Nessun bonus alle incursioni: lo stereotipo del predone non è un tratto del modello.",
    sources: [{ work: "Encyclopaedia Britannica", entry: "Viking" }],
    dataVersion: V,
  },
];

/** Validated, frozen catalog. A malformed entry fails at import time, never at runtime. */
export const HISTORICAL_IDENTITIES: readonly HistoricalIdentityDefinition[] = Object.freeze(
  RAW_CATALOG.map((identity) => Object.freeze(historicalIdentitySchema.parse(identity))),
);

export const IDENTITY_BY_KEY: ReadonlyMap<string, HistoricalIdentityDefinition> = new Map(
  HISTORICAL_IDENTITIES.map((identity) => [identity.key, identity]),
);

export function getIdentity(key: string | null | undefined): HistoricalIdentityDefinition | undefined {
  return key ? IDENTITY_BY_KEY.get(key) : undefined;
}

/** Naming profile of a political instance, `null` for procedural and legacy tribes. */
export function namingFor(tribe: { identityId: string | null }) {
  return getIdentity(tribe.identityId)?.namingProfile ?? null;
}
