import { getCivilizationHistoryService } from "@/lib/services/identity-service";
import { errorResponse, ok, parse, parseWorldId, searchParams } from "@/lib/utils/api";
import { AppError } from "@/lib/utils/errors";
import { civilizationHistoryQuerySchema, civilizationIdSchema } from "@/lib/validation/identity";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

type Context = { params: Promise<{ worldId: string; civilizationId: string }> };

/** History generated by the simulation for one people: events, discoveries, leaders. */
export async function GET(request: Request, context: Context) {
  try {
    const params = await context.params;
    const worldId = parseWorldId(params.worldId);
    const parsed = civilizationIdSchema.safeParse(params.civilizationId);
    if (!parsed.success) throw new AppError("NOT_FOUND", "Civiltà non trovata");
    const query = parse(civilizationHistoryQuerySchema, searchParams(request));
    return ok(await getCivilizationHistoryService(worldId, parsed.data, query));
  } catch (error) {
    return errorResponse(error);
  }
}
